
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action NewAction;

	private global::Gtk.Action OpenAction;

	private global::Gtk.Action SaveAction;

	private global::Gtk.Action SaveAsAction;

	private global::Gtk.Action SettingsAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action TimelineAction;

	private global::Gtk.Action AddAction;

	private global::Gtk.Action EntryAction;

	private global::Gtk.Action RemoveSelectedAction;

	private global::Gtk.Action RefreshWeatherForecastAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.VBox vbox2;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.Table table1;

	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.NewAction = new global::Gtk.Action("NewAction", global::Mono.Unix.Catalog.GetString("New"), null, null);
		this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New");
		w1.Add(this.NewAction, null);
		this.OpenAction = new global::Gtk.Action("OpenAction", global::Mono.Unix.Catalog.GetString("Open"), null, null);
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open");
		w1.Add(this.OpenAction, null);
		this.SaveAction = new global::Gtk.Action("SaveAction", global::Mono.Unix.Catalog.GetString("Save"), null, null);
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save");
		w1.Add(this.SaveAction, null);
		this.SaveAsAction = new global::Gtk.Action("SaveAsAction", global::Mono.Unix.Catalog.GetString("Save as..."), null, null);
		this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save as...");
		w1.Add(this.SaveAsAction, null);
		this.SettingsAction = new global::Gtk.Action("SettingsAction", global::Mono.Unix.Catalog.GetString("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Settings");
		w1.Add(this.SettingsAction, null);
		this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.ExitAction, null);
		this.TimelineAction = new global::Gtk.Action("TimelineAction", global::Mono.Unix.Catalog.GetString("Timeline"), null, null);
		this.TimelineAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Timeline");
		w1.Add(this.TimelineAction, null);
		this.AddAction = new global::Gtk.Action("AddAction", global::Mono.Unix.Catalog.GetString("Add..."), null, null);
		this.AddAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Add...");
		w1.Add(this.AddAction, null);
		this.EntryAction = new global::Gtk.Action("EntryAction", global::Mono.Unix.Catalog.GetString("Entry"), null, null);
		this.EntryAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Entry");
		w1.Add(this.EntryAction, null);
		this.RemoveSelectedAction = new global::Gtk.Action("RemoveSelectedAction", global::Mono.Unix.Catalog.GetString("Remove selected"), null, null);
		this.RemoveSelectedAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Remove selected");
		w1.Add(this.RemoveSelectedAction, null);
		this.RefreshWeatherForecastAction = new global::Gtk.Action("RefreshWeatherForecastAction", global::Mono.Unix.Catalog.GetString("Refresh weather forecast"), null, null);
		this.RefreshWeatherForecastAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Refresh weather forecast");
		w1.Add(this.RefreshWeatherForecastAction, null);
		this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.AboutAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='NewAction' action='NewAction'/><menuitem name='OpenAction' action='OpenAction'/><menuitem name='SaveAction' action='SaveAction'/><menuitem name='SaveAsAction' action='SaveAsAction'/><menuitem name='SettingsAction' action='SettingsAction'/><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='TimelineAction' action='TimelineAction'><menu name='AddAction' action='AddAction'><menuitem name='EntryAction' action='EntryAction'/></menu><menuitem name='RemoveSelectedAction' action='RemoveSelectedAction'/><menuitem name='RefreshWeatherForecastAction' action='RefreshWeatherForecastAction'/></menu><menu name='AboutAction' action='AboutAction'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox2.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w3 = new global::Gtk.Viewport();
		w3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(1)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		w3.Add(this.table1);
		this.scrolledwindow1.Add(w3);
		this.vbox2.Add(this.scrolledwindow1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow1]));
		w6.Position = 1;
		// Container child vbox2.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox2.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.statusbar1]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.Add(this.vbox2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 513;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
